language: bash
sudo: required

services:
  - docker
  
deploy:
  provider: script
  script: bash publish-docker-17.03.1-ce-kubectl-v1.11.0-helm-v2.7.2-node-v12.13.1.sh
  on:
    branch: release  
    tags: true
