apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: vsts-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsts-agent
  template:
    metadata:
      labels:
        app: vsts-agent
    spec:
      containers:
      - name: vsts-agent
        image: oleconsignado/otc-vsts-agent-dotnet-k8s:docker-17.03.1-ce-kubectl-v1.9.0-helm-v2.7.2-v1.1
        env:
          - name: VSTS_ACCOUNT
            value: jose@your-organization
            # In order to create a secret with vsts token, execute:
            # kubectl create secret generic vsts-token --from-literal=token=<VSTS-TOKEN-HERE>
          - name: VSTS_TOKEN
            valueFrom:
              secretKeyRef:
                name: vsts-token
                key: token
          - name: VSTS_POOL
            value: Kubernetes
          - name: TFS_HOST
            value: your-organization.visualstudio.com
        resources:
          requests:
            memory: 256Mi
            cpu: 1
          limits:
            memory: 512Mi
            cpu: 1
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock
      nodeSelector:                          # Optional (use only if you want to use a single node to build images)
        kubernetes.io/hostname: olekbnhml01  # Put the node's hostname here
