#!/bin/bash

set -e

include_source=$1

if [ -z "$include_source" ]
then
	echo "Usage: $0 include_source" >> /dev/stderr
	exit 3
fi

otc-task --download-only $OTC_TASK_VERSION_PATH_SEGMENT $include_source